name: open_url
description: Open a URL on the user's default application. Helpful on DartVM, on Flutter use url_launcher instead.
version: 2.0.1
homepage: https://github.com/renatoathaydes/open_url

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
